// Generated by CoffeeScript 1.8.0
var fs = require('fs');
var path = require('path');

var webpack = require('webpack');

var basic = require('./webpack.config');


Object.assign(basic, {

  plugins: [
    new webpack.DefinePlugin({
      __DEBUG__: false
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  ],

  output: {
    path: path.resolve(__dirname, './js'),
    publicPath: "/js/",
    filename: 'index.js'
  },
  devtool:false
})

module.exports = basic;