// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var base = require('./webpack.config');

base.output.publicPath = '';

Object.assign(base,{
  entry : {
    index: [
      path.resolve(__dirname, './public/back/scripts/main.jsx')
    ],
  },
  module: {
    loaders: [
      {
        test:/\.jsx|\.js$/,
        loader:'babel',
        query:{
          compact:false
        }
      },
      {
        test: /\.(scss|css|sass)$/,
        exclude: /node_modules|bower_components/,
        loader: ExtractTextPlugin.extract('style','css!sass')
      },
      {
        test:/\.ttf|otf$/,
        loaders:['file?name=[name].[ext]']
      }
    ]
  },
  plugins:[
    new webpack.DefinePlugin({
      env: {
        isDevelopment:false
      },
      __DEV__:false,
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress:{
        warnings:false
      }
    }),
    new ExtractTextPlugin('css/[name].css')
  ]
})



module.exports = base;