// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

module.exports = {
  webpackDevPort: webpackDevPort,
  resolve: {
    extensions: ['', '.js','.jsx','.scss'],
  },
  externals:{

  },
  entry: {
    index: [
      path.resolve(__dirname, './public/js/main.js'),
      'webpack-hot-middleware/client',
    ]
  },
  output: {
    path: path.resolve(__dirname, './public/dist/'),
    publicPath: "/dist",
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test:/\.jsx|\.js$/,
        exclude: /node_modules|bower_components/,
        loader:'babel'
      },
      {
        test: /\.ejs$/,
        exclude: /node_modules|bower_components/,
        loader: 'ejs-loader?variable=data'
      },
      {
        test:/\.scss$/,
        exclude: /node_modules|bower_components/,
        loaders:['style','css','sass-loader']
      },
      {
        test:/\.jpg|png$/,
        exclude: /node_modules|bower_components/,
        loaders:['url','file']
      },
      {
        test:/\.ttf|otf|eot|svg$/,
        exclude: /node_modules|bower_components/,
        loaders:['url','file']
      }
    ]
  },
  plugins:[
    new webpack.DefinePlugin({
      env:{
        isDevelopment:true
      }
    }),
    new webpack.HotModuleReplacementPlugin()
  ],

  devtool: 'source-map'
};

//# sourceMappingURL=webpack.config.js.map
